### ISSUE TITLE
[Feature Request] a non-async way to poll a JoinHandle for a result

### ISSUE THREAD

**Issue by kyren** [smol-rs/async-task#1]
Currently I'm working on a project that mixes async and sync code, and my general pattern for dealing with this has been to create [oneshot channels](https://docs.rs/futures/0.3.5/futures/channel/oneshot/index.html) and spawn tasks which send to the oneshot channel, and on the sync side, poll for results using [try_recv](https://docs.rs/futures/0.3.5/futures/channel/oneshot/struct.Receiver.html#method.try_recv).

Would it be possible or sensible to have such a non-async poll method directly on the `JoinHandle` returned by the executor?  Can I get the same result by using `Future::poll` with a no-op Waker?

Right now there are only a few sanctioned "sync <-> async bridge" methods like oneshot's try_recv, and I'm not sure how much the rust async ecosystem in general is aware of this use case.  None of the popular executors I see return join handles that can be non-async polled.  They may all work with no-op wakers, but my worry would be that I would somehow cause a panic by polling without honoring waking, but maybe that's guaranteed not to happen?  It would also be nicer if there was a sanctioned, optimized way to do this generally.

This pattern shows up a lot when you have a hard / soft real-time loop that is waiting on the result of async code, so games and stuff like games.

**Comment by ghost** [comment]
Oh hi, I loved your RustConf 2018 talk! 👋 

The `futures` crate provides a method to poll futures in a way similar to `try_recv()` - and it's called [`now_or_never()`](https://docs.rs/futures/0.3.5/futures/future/trait.FutureExt.html#method.now_or_never). Example:

```rust
let val: Option<T> = my_future.now_or_never();
```

Note that this consumes `my_future`, but you can avoid consuming it by polling `&mut future` instead. This works because if type `F` is a `Future`, then `&mut F` is also a `Future`:

```rust
let val: Option<T> = (&mut my_future).now_or_never();
```

Of course, you can also block on the result:

```rust
let val: T = futures::executor::block_on(my_future);
```

Would that work for you?

We could also add a new method `JoinHandle::try_join()` that would internally just do the `now_or_never()` thing - I personally didn't find a need for it but let me know if that's something you'd like to see in the crate!

**Comment by kyren** [comment]
> Oh hi, I loved your RustConf 2018 talk! 👋

Thank you, that's very kind of you, I'm glad you liked it!  I love smol 😄 

> The futures crate provides a method to poll futures in a way similar to try_recv() - and it's called now_or_never(). Example:

I didn't even think of that, I even asked around about it and I somehow missed now_or_never.  It works exactly how I would have written it, with a no-op waker.  That must always be guaranteed to work then?  Maybe a PR to the [future docs](https://doc.rust-lang.org/stable/std/future/trait.Future.html) is in order, it doesn't seem to address that calling `Future::poll` too early should not cause panics (or I'm blind and I missed it).

> Of course, you can also block on the result:

No blocking would be very bad, it needs to poll it every frame.

> We could also add a new method JoinHandle::try_join() that would internally just do the now_or_never() thing - I personally didn't find a need for it but let me know if that's something you'd like to see in the crate!

Honestly now that I know about `now_or_never` I think the correct place to put it is on `FutureExt` but a version that doesn't consume the future and with a different name.

One of the other things I didn't mention before is that I'm always wary of calling certain functions outside of the context of a task unless they're explicitly advertised this way, because I've encountered panics before with runtimes that assume global variables are populated from being inside their own runtime.  If for example `JoinHandle` here ever decided to opportunistically call `Future::poll` on its target future somehow that might trigger panics if the target future has weird requirements.  If that's something that has a chance of happening then maybe a specific method would be worth it that was guaranteed *not* to do that?  Otherwise, I think this is either a thing to add to `futures` or it was just a *me* issue 😄 

Edit: really, this is part of a larger async <-> sync bridging issue that I've been having with runtimes in general, unexpected panicking has been part of it.  I didn't know where to make an issue so I just picked a starting place.  I'm sure a lot of this doesn't apply to async-task or smol directly, I'm just trying to come up with solutions where I might have to mix runtimes.  I really appreciate you taking your time to talk this through with me though!

**Comment by ghost** [comment]
> I didn't even think of that, I even asked around about it and I somehow missed now_or_never. It works exactly how I would have written it, with a no-op waker.

It's not an easily discoverable method, unfortunately, especially given how useful it is. I agree the docs need a bit of polish in that area.

> One of the other things I didn't mention before is that I'm always wary of calling certain functions outside of the context of a task unless they're explicitly advertised this way, because I've encountered panics before with runtimes that assume global variables are populated from being inside their own runtime. If for example `JoinHandle` here ever decided to opportunistically call `Future::poll` on its target future somehow that might trigger panics if the target future has weird requirements.

The good news is that you don't need to worry about polled `JoinHandle` being inside the wrong context. And the reason is that join handles don't poll the spawned future when polled - they only check whether the future has been completed, and if so, they then retrieve the result.

Polling a join handle is a lot like receiving a message from a channel. You can use channels anywhere in the program because they're aren't tied to any executor. Perhaps surprisingly, join handles aren't either! :)

The difference between what's *inside* and *outside* the runtime is somewhat specific to tokio - other runtimes typically don't have the concept of *runtime contexts* so you can use spawn tasks or do I/O from literally anywhere in the program. There are pros and cons to both designs, however. My personal opinion is that runtime contexts are more pain than gain. There is some ongoing discussion on that in https://github.com/tokio-rs/tokio/issues/2435

Glad I can help and always happy to answer more questions :) Hearing your thought process and struggles with async programming is also very helpful to me because it gives me a better sense around designing runtimes to be simpler and easier to understand.

**Comment by kyren** [comment]
> The good news is that you don't need to worry about polled JoinHandle being inside the wrong context. And the reason is that join handles don't poll the spawned future when polled - they only check whether the future has been completed, and if so, they then retrieve the result.

Yeah I was aware that it doesn't do such a thing now, it was more of a concern about whether that was ever a future possibility but it sounds like it's not 👍. 

> Polling a join handle is a lot like receiving a message from a channel. You can use channels anywhere in the program because they're aren't tied to any executor. Perhaps surprisingly, join handles aren't either! :)

That's wonderful, that's exactly the API I would want.

> The difference between what's inside and outside the runtime is somewhat specific to tokio - other runtimes typically don't have the concept of runtime contexts so you can use spawn tasks or do I/O from literally anywhere in the program. There are pros and cons to both designs, however. My personal opinion is that runtime contexts are more pain than gain. There is some ongoing discussion on that in tokio-rs/tokio#2435

I didn't want to call out tokio specifically, but yeah the problems I've had are pretty much exactly what's in that issue.  This shows up a lot of course when more than half of your program is not in the tokio context.  When you want to construct a task, you have to remember to call `tokio::time::delay_for` and similar methods *only* inside the task and not outside of it, even if it would be natural to call that method and then move the result into the task, and nothing about the types suggests that it's problematic.  These are probably "niche" concerns since many programs will be pure async but if you fall into that niche it's pretty un-ergonomic imo, so I would agree that runtime contexts are more pain than gain!

> Glad I can help and always happy to answer more questions :) Hearing your thought process and struggles with async programming is also very helpful to me because it gives me a better sense around designing runtimes to be simpler and easier to understand.

Yeah smol is absolutely in the right direction here.  And you're very welcome, I'm quite happy to share my thoughts and complaints, thank you for taking the time to listen to them!

**Comment by kyren** [comment]
I'm going to close this issue since I think the more appropriate place to address it (if any) is the `FutureExt` trait.
